[build]
  publish = "public"
  # command = "cd exampleSite && hugo --gc --themesDir ../.."
  # command = "hugo --minify --themesDir ../.."
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.87.0" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.87.0" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
  HUGO_VERSION = "0.87.0"
  
# [build.environment]
  # HUGO_VERSION = "0.87.0"
  # HUGO_THEME = "repo"
  # HUGO_THEME = "meghna-hugo"
  # HUGO_BASEURL = "/"
  # HUGO_BASEURL = "https://"